# Generated by Django 6.0.6 on 2026-07-12 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('products', models.ManyToManyField(blank=True, help_text='Các sản phẩm mà người dùng này đã thêm vào danh sách yêu thích.', related_name='wishlisted_by', to='products.product', verbose_name='Sản phẩm yêu thích')),
                ('user', models.OneToOneField(help_text='Mỗi người dùng chỉ có đúng một danh sách yêu thích.', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Danh sách yêu thích',
                'verbose_name_plural': 'Danh sách yêu thích',
            },
        ),
    ]
