# Generated by Django 4.2.23 on 2026-08-02 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_product_care_instructions_product_sku_product_specs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlassesOverlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Ảnh chụp thẳng mặt, nền trong suốt (kênh alpha), dùng để dán lên mặt qua webcam.', upload_to='tryon/glasses/', verbose_name='Ảnh kính (PNG nền trong suốt)')),
                ('width_ratio', models.FloatField(default=1.6, help_text='CHỈ dùng khi thuật toán không tự tìm được tâm 2 tròng kính trong ảnh. Bề rộng kính hiển thị = khoảng cách 2 mắt × số này.', verbose_name='Tỉ lệ bề rộng (chế độ dự phòng)')),
                ('vertical_offset', models.FloatField(default=0.0, help_text='CHỈ dùng ở chế độ dự phòng. Độ lệch dọc của tâm kính so với trung điểm 2 mắt, tính theo tỉ lệ khoảng cách 2 mắt (dương = xuống dưới).', verbose_name='Độ lệch dọc (chế độ dự phòng)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật gần nhất')),
                ('product', models.OneToOneField(help_text='Sản phẩm kính mà ảnh AR này đại diện cho.', on_delete=django.db.models.deletion.CASCADE, related_name='glasses_overlay', to='products.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Ảnh kính AR',
                'verbose_name_plural': 'Ảnh kính AR (thử kính ảo)',
                'ordering': ['product__name'],
            },
        ),
    ]
