# Generated by Django 4.2.23 on 2026-09-11 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_slug_alter_product_category_and_more'),
        ('tryon', '0003_seed_dublin_glasses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glassesoverlay',
            name='image',
            field=models.ImageField(upload_to='tryon/glasses/', verbose_name='Ảnh kính (PNG nền trong suốt)'),
        ),
        migrations.AlterField(
            model_name='glassesoverlay',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='glasses_overlay', to='products.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='glassesoverlay',
            name='vertical_offset',
            field=models.FloatField(default=0.0, verbose_name='Độ lệch dọc (chế độ dự phòng)'),
        ),
        migrations.AlterField(
            model_name='glassesoverlay',
            name='width_ratio',
            field=models.FloatField(default=1.6, verbose_name='Tỉ lệ bề rộng (chế độ dự phòng)'),
        ),
    ]
