-- =============================================================
-- Seed du lieu san pham kinh mat (nguon: intl.lespecs.com)
-- Danh muc duoc gan theo dang gong kinh (Frame Shape), moi san
-- pham co them gioi tinh (gender: nu/nam/unisex) de loc tren
-- trang chu. Anh san pham da duoc tai ve media/products/.
-- =============================================================

SET NAMES utf8mb4;

-- ---------- Danh muc theo dang gong kinh ----------
INSERT INTO products_category (name, slug, created_at) SELECT 'Phi Công (Aviator)', 'phi-cong-aviator', NOW() WHERE NOT EXISTS (SELECT 1 FROM products_category WHERE slug = 'phi-cong-aviator');
INSERT INTO products_category (name, slug, created_at) SELECT 'Mắt Mèo (Cat-Eye)', 'mat-meo-cat-eye', NOW() WHERE NOT EXISTS (SELECT 1 FROM products_category WHERE slug = 'mat-meo-cat-eye');
INSERT INTO products_category (name, slug, created_at) SELECT 'D-Frame', 'd-frame', NOW() WHERE NOT EXISTS (SELECT 1 FROM products_category WHERE slug = 'd-frame');
INSERT INTO products_category (name, slug, created_at) SELECT 'Bát Giác (Octagon)', 'bat-giac-octagon', NOW() WHERE NOT EXISTS (SELECT 1 FROM products_category WHERE slug = 'bat-giac-octagon');
INSERT INTO products_category (name, slug, created_at) SELECT 'Oval', 'oval', NOW() WHERE NOT EXISTS (SELECT 1 FROM products_category WHERE slug = 'oval');
INSERT INTO products_category (name, slug, created_at) SELECT 'Chữ Nhật (Rectangle)', 'chu-nhat-rectangle', NOW() WHERE NOT EXISTS (SELECT 1 FROM products_category WHERE slug = 'chu-nhat-rectangle');
INSERT INTO products_category (name, slug, created_at) SELECT 'Tròn (Round)', 'tron-round', NOW() WHERE NOT EXISTS (SELECT 1 FROM products_category WHERE slug = 'tron-round');
INSERT INTO products_category (name, slug, created_at) SELECT 'Khiên (Shield)', 'khien-shield', NOW() WHERE NOT EXISTS (SELECT 1 FROM products_category WHERE slug = 'khien-shield');
INSERT INTO products_category (name, slug, created_at) SELECT 'Vuông (Square)', 'vuong-square', NOW() WHERE NOT EXISTS (SELECT 1 FROM products_category WHERE slug = 'vuong-square');
INSERT INTO products_category (name, slug, created_at) SELECT 'Wrap', 'wrap', NOW() WHERE NOT EXISTS (SELECT 1 FROM products_category WHERE slug = 'wrap');

-- ---------- San pham ----------
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Dirty Magic', 'dirty-magic-matte-black-tort-brown-mono-lsp1100201', 'DIRTY MAGIC is a bold unisex style with a sharp rectangular silhouette that exudes effortless confidence. Its oversized D-frame design delivers a distinctive edge while complementing a wide range of face shapes, making it the perfect blend of versatility and attitude.
- Finished in a matte black and tort frame with brown mono lenses.
- Made using BPA free polymer plastic which is lightweight, durable and impact resistant.
- Fitted with shatterproof and scratch resistant polycarbonate lenses.', 762000, 25, 'products/dirty-magic-matte-black-tort-brown-mono-lsp1100201.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'd-frame'), NULL, 'nam' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'dirty-magic-matte-black-tort-brown-mono-lsp1100201');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Tweedledum', 'tweedledum-matte-tort-matte-black-smoke-mono-lsp1402184', 'TWEEDLEDUM is a bold, modern rectangle with round-profile metal temples, delivering a strong, masculine edge to a timeless design.
- Finished in a matte tort and matte black frame with smoke mono lenses.
- Made using BPA free polymer plastic which is lightweight, durable and impact resistant.
- Fitted with shatterproof and scratch resistant polycarbonate lenses.', 1905000, 14, 'products/tweedledum-matte-tort-matte-black-smoke-mono-lsp1402184.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'd-frame'), NULL, 'nam' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'tweedledum-matte-tort-matte-black-smoke-mono-lsp1402184');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Dark Magic', 'dark-magic-black', 'Give a bold and confident look with our DARK MAGIC d frame sunglasses. Featuring a bold and flat brow bar and classic Le Specs flagstripe pin badge, these frames offer a large and comfortable fit.
- Finished in a black frame with smoke mono polarized lenses.
- A lightweight, durable and impact resistant polycarbonate frame.
- Fitted with polarized lenses to eliminate unwanted reflective glare.', 1905000, 30, 'products/dark-magic-black.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'd-frame'), NULL, 'nam' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'dark-magic-black');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Master Tamers', 'master-tamers-matte-black-smoke-mono-lsp1602163', 'This masculine squared off d-frame sunglasses features a stylish, slightly oversized matte black frame. Featuring a premium tubular metal temple, this frame offers a comfortable fit. 
- Finished in a matte black frame with smoke mono lenses.
- Made using BPA free polymer plastic which is lightweight, durable and impact resistant.
- Fitted with shatterproof and scratch resistant polycarbonate lenses.', 1778000, 46, 'products/master-tamers-matte-black-smoke-mono-lsp1602163.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'd-frame'), NULL, 'nam' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'master-tamers-matte-black-smoke-mono-lsp1602163');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Broski', 'broski-black-amber-tint', 'Our BROKSI sunglasses are an update to the classic D-frame silhouette with vintage-inspired proportions and refined angles. Designed with slimline profile and wider fit for all face shapes and sizes, these d-frame sunglasses feature subtle flag stripe metal rivet detailing.
- Finished in a black frame with amber tint lenses.
- A lightweight, durable and impact resistant frame.
- Fitted with shatterproof and scratch resistant polycarbonate lenses.', 508000, 8, 'products/broski-black-amber-tint.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'd-frame'), NULL, 'nam' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'broski-black-amber-tint');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Tweedledum', 'tweedledum-matte-black-khaki-mono-polarised-lsp1702030', 'TWEEDLEDUM is a bold, modern rectangle with round-profile metal temples, delivering a strong, masculine edge to a timeless design.
- Finished in a matte black frame with khaki mono polarized lenses.
- Made using BPA free polymer plastic which is lightweight, durable and impact resistant.
- Fitted with polarized lenses to eliminate unwanted reflective glare.', 2159000, 9, 'products/tweedledum-matte-black-khaki-mono-polarised-lsp1702030.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'd-frame'), NULL, 'nam' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'tweedledum-matte-black-khaki-mono-polarised-lsp1702030');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Broski', 'broski-toffee-tort', 'Our BROKSI sunglasses are an update to the classic D-frame silhouette with vintage-inspired proportions and refined angles. Designed with slimline profile and wider fit for all face shapes and sizes, these d-frame sunglasses feature subtle flag stripe metal rivet detailing.
- Finished in a toffee tort frame with khaki mono lenses.
- A lightweight, durable and impact resistant frame.
- Fitted with shatterproof and scratch resistant polycarbonate lenses.', 1016000, 57, 'products/broski-toffee-tort.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'd-frame'), NULL, 'nam' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'broski-toffee-tort');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Numero Seis', 'numero-seis-bright-silver-moss-grad', 'Exuding a timeless and effortless aesthetic, our NÚMERO SEIS sunglasses adopt a modern approach to the retro aviator silhouette. Made from premium high-quality metal, this frame features metal tri-claw end piece detailing and moulded custom nose bridge, each finished with a rounded, luxurious hand polished effect. Each pair is completed with three dimensionally crafted 6mm acetate tips with contoured lines for a comfortable fit.
- Finished in a luxurious bright silver frame with moss...', 4064000, 39, 'products/numero-seis-bright-silver-moss-grad.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'phi-cong-aviator'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'numero-seis-bright-silver-moss-grad');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Numero Seis', 'numero-seis-bright-gold-umber-mono', 'Exuding a timeless and effortless aesthetic, our NÚMERO SEIS sunglasses adopt a modern approach to the retro aviator silhouette. Made from premium high-quality metal, this frame features metal tri-claw end piece detailing and moulded custom nose bridge, each finished with a rounded, luxurious hand polished effect. Each pair is completed with three dimensionally crafted 6mm acetate tips with contoured lines for a comfortable fit.
- Finished in a luxurious bright gold frame with umber mono...', 4064000, 11, 'products/numero-seis-bright-gold-umber-mono.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'phi-cong-aviator'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'numero-seis-bright-gold-umber-mono');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Numero Seis', 'numero-seis-bright-silver-smoke-tint', 'Exuding a timeless and effortless aesthetic, our NÚMERO SEIS sunglasses adopt a modern approach to the retro aviator silhouette. Made from premium high-quality metal, this frame features metal tri-claw end piece detailing and moulded custom nose bridge, each finished with a rounded, luxurious hand polished effect. Each pair is completed with three dimensionally crafted 6mm acetate tips with contoured lines for a comfortable fit.
- Finished in a luxurious bright silver frame with smoke tint...', 4064000, 28, 'products/numero-seis-bright-silver-smoke-tint.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'phi-cong-aviator'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'numero-seis-bright-silver-smoke-tint');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Fortune Teller', 'fortune-teller-sand', 'Embrace vintage appeal with our FORTUNE TELLER aviator sunglasses. Featuring a 70s-inspired silhouette and unique contours, these oversized sunglasses offer a flattering unisex fit. With bold frame detailing and refined metal accents, they deliver a striking yet effortless look.
- Finished in a sand frame with jade gradient lenses.
- Made using BPA free polymer plastic which is lightweight, durable and impact resistant.
- Fitted with shatterproof and scratch resistant polycarbonate lenses.', 1016000, 42, 'products/fortune-teller-sand.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'phi-cong-aviator'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'fortune-teller-sand');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'The Whisperer', 'the-whisperer-black-polarised', 'Designed with micro proportions, THE WHISPERER is this season’s must-have update to the classic cat-eye. Featuring a sleek, sculpted frame and distinctive angled lenses, this style delivers a bold yet effortless statement. The refined shape and lightweight construction make it perfect for everyday styling, from off-duty looks to weekend wear.
- Finished in a black frame with smoke mono polarized lenses.
- Made using BPA free polymer plastic which is lightweight, durable and impact...', 2286000, 8, 'products/the-whisperer-black-polarised.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'mat-meo-cat-eye'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'the-whisperer-black-polarised');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Air Heart', 'air-heart-oatmeal-lsp2102333', 'A favourite of Meghan Markle and Olivia Palermo, the AIR HEART silhouette is an iconic Le Specs style. With oversized and dramatic proportions reminiscent of a cat eye, the style is designed with a thick semi-translucent tan frame and luxurious metal top bar inlay, then fitted with premium zero base smoke flat lenses. The perfect statement sunglass to suit all face shapes.
- Finished in an oatmeal frame with khaki gradient lenses.
- Made using BPA free polymer plastic which is lightweight,...', 1524000, 37, 'products/air-heart-oatmeal-lsp2102333.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'mat-meo-cat-eye'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'air-heart-oatmeal-lsp2102333');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Air Heart', 'air-heart-black-gold-khaki-mono-lsp1602175', 'A favourite of Meghan Markle and Olivia Palermo, the AIR HEART silhouette is an iconic Le Specs style. With oversized and dramatic proportions reminiscent of a cat eye, the style is designed with a thick semi-translucent tan frame and luxurious metal top bar inlay, then fitted with premium zero base smoke flat lenses. The perfect statement sunglass to suit all face shapes.
- Finished in a black and gold frame with khaki mono lenses.
- Made using BPA free polymer plastic which is lightweight,...', 2032000, 18, 'products/air-heart-black-gold-khaki-mono-lsp1602175.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'mat-meo-cat-eye'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'air-heart-black-gold-khaki-mono-lsp1602175');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Hypnosis', 'hypnosis-black-lsp2452328', 'Our HYPNOSIS cat-eye sunglasses are a summer wardrobe staple with sweeping lines and slimline proportions. This sleek feminine style will look fab on all face shapes, featuring a midsize fit and detailed with our classic flag stripe hardware on both temples.
- Finished in a black frame with smoke mono lenses.
- Made using BPA free polymer plastic which is lightweight, durable and impact resistant.
- Fitted with shatterproof and scratch resistant polycarbonate lenses.', 1905000, 7, 'products/hypnosis-black-lsp2452328.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'mat-meo-cat-eye'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'hypnosis-black-lsp2452328');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Numero Nueve', 'numero-nueve-pink-salt', 'With striking lines and confident proportions, our NUMERO NUEVE sunglasses deliver a bold take on the modern rectangle silhouette. Made from bespoke custom 8mm & 6mm acetates, this frame highlights delicate chamfering detail meticulously added to every aspect of the frame, providing a soft and rounded luxurious, hand polished look and feel. Each pair is finished with Le Specs signature three dimensionally crafted infinity flagstripe metal decal and iconic single flagstripe inspired rounded...', 2032000, 10, 'products/numero-nueve-pink-salt.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'd-frame'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'numero-nueve-pink-salt');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Numero Tres', 'numero-tres-dune-lsl2450908', 'With striking lines and prominent proportions, our NUMERO TRES modern rectangle sunglasses offer a petite 90s inspired look. Made from bespoke custom 8mm & 6mm acetates, this frame highlights delicate chamfering detail meticulously added to every aspect of the frame, providing a soft and rounded luxurious, hand polished look and feel. Each pair is finished with Le Specs signature three dimensionally crafted Infinity flagstripe metal decal and iconic single flagstripe inspired rounded rivet...', 2540000, 32, 'products/numero-tres-dune-lsl2450908.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'd-frame'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'numero-tres-dune-lsl2450908');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Cubito +', 'cubito-sand', 'Cubito is a structured square frame with bold proportions and sharp lines. Its thick-set silhouette and defined angles give it a strong, confident presence, while the flatter brow and wider temples reinforce its modernist edge. A statement style that blends classic square eyewear with contemporary attitude, this frame is finished with a horizontal inlaid hardware with debossed flagstripe and rivet detailing.
- Finished in a sand frame with brown gradient lenses.
- A lightweight, durable and...', 1905000, 31, 'products/cubito-sand.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'd-frame'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'cubito-sand');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Numero Nueve', 'numero-nueve-teak', 'With striking lines and confident proportions, our NUMERO NUEVE sunglasses deliver a bold take on the modern rectangle silhouette. Made from bespoke custom 8mm & 6mm acetates, this frame highlights delicate chamfering detail meticulously added to every aspect of the frame, providing a soft and rounded luxurious, hand polished look and feel. Each pair is finished with Le Specs signature three dimensionally crafted infinity flagstripe metal decal and iconic single flagstripe inspired rounded...', 2794000, 9, 'products/numero-nueve-teak.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'd-frame'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'numero-nueve-teak');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Lunita', 'lunita-tort-blue-light-lens', 'Sleek and sculptural, LUNITA elevates the classic oval silhouette with a bold contoured front and refined metal temples. Designed with cut-out detailing that offers a light, modern feel, this style delivers a distinctive feminine look finished with Le Specs’ signature polished hardware.
- Finished in a tort frame.
- Made using BPA free polymer plastic which is lightweight, durable and impact resistant.
- Fitted with anti-blue light lenses that filter 30% of blue light. Our lenses are made...', 1905000, 20, 'products/lunita-tort-blue-light-lens.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'bat-giac-octagon'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'lunita-tort-blue-light-lens');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Outta Love', 'outta-love-cookie-tort-lsp2202446', 'Exuding ''90s confidence, our iconic OUTTA LOVE silhouette offers a minimal nineties look. This petite, slimline oval silhouette features a modern flat profile and signature Le Specs gold metal hardware, and is just the right size to complement your face without hiding your best features.
Designed for a smaller, more petite fit, perfect for those with narrower face shapes.
- Finished in a cookie tort frame with smokey brown mono lenses.
- A lightweight, durable and impact resistant...', 1905000, 10, 'products/outta-love-cookie-tort-lsp2202446.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'oval'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'outta-love-cookie-tort-lsp2202446');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Love Train', 'love-train-silver', 'Embracing the early nineties aesthetic, our LOVE TRAIN slimline oval sunglasses exude a sense of minimalistic elegance. Featuring striking semi-flat lenses and micro proportions, this frame is finished with adjustable nose pads for a tailored fit.
- Finished in a silver frame with lilac tint lenses.
- Sturdy metal frame fitted with allergy-free cushioned PVC nose pads. 
- Fitted with shatterproof and scratch resistant polycarbonate lenses.', 2032000, 40, 'products/love-train-silver.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'oval'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'love-train-silver');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Lunar', 'lunar-tan', 'ALÉMAIS x Le Specs Luxe exclusive. Defined by its narrow proportions, subtly upswept corners and sleek almond-like silhouette, the LUNAR sunglasses offer a distinctly modern take on 90s minimalism.
- Finished in a tan frame with light brown gradient lenses.
- Carefully crafted from handmade cellulose acetate with a luxurious touch and comfortable fit.
- Fitted with premium CR-39 lenses which offer superior optical clarity, and provide 100% UVA / UVB protection.
- Packaged with Alemais Le...', 5080000, 32, 'products/lunar-tan.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'oval'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'lunar-tan');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Magnifique', 'magnifique-black-lsp2202529', 'Our MAGNIFIQUE oval sunglasses offer a minimalist Y2K aesthetic with narrow proportions. Designed with premium vintage-inspired pinstripe metal temples, this slimline style is just the right size to complement your face without hiding your best features.
- Finished in a black frame with green mono lenses.
- Made using BPA free polymer plastic which is lightweight, durable and impact resistant.
- Fitted with shatterproof and scratch resistant polycarbonate lenses.', 1905000, 8, 'products/magnifique-black-lsp2202529.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'oval'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'magnifique-black-lsp2202529');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Honey Pot', 'honey-pot-amber-tort', 'Inspired by nostalgic Y2K style, our HONEY POT sunglasses give a playful update to the slim rectangular silhouette. Featuring softly bevelled edges and a smooth, rounded profile, this midsize frame offers easy unisex proportions and is finished with Le Specs’ signature metal temple detail for a clean modern touch.
- Finished in an amber tort frame with dusty blue tint lenses.
- A lightweight, durable and impact resistant polycarbonate frame.
- Fitted with shatterproof and scratch resistant...', 1651000, 57, 'products/honey-pot-amber-tort.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'chu-nhat-rectangle'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'honey-pot-amber-tort');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Honey Pot', 'honey-pot-tort', 'Inspired by nostalgic Y2K style, our HONEY POT sunglasses give a playful update to the slim rectangular silhouette. Featuring softly bevelled edges and a smooth, rounded profile, this midsize frame offers easy unisex proportions and is finished with Le Specs’ signature metal temple detail for a clean modern touch.
- Finished in a tort frame with brown mono lenses.', 1651000, 41, 'products/honey-pot-tort.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'chu-nhat-rectangle'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'honey-pot-tort');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Numero Diez', 'numero-diez-champagne-velvet', 'With strong, sharp lines and refined narrow proportions, our NÚMERO DIEZ sunglasses deliver a confident and elevated interpretation of the modern rectangular silhouette. Featuring an ultra-flat 0-base lens and meticulous chamfering throughout, this frame is crafted from bespoke custom 8mm & 6mm acetates, balancing bold structure with subtle refinement. This frame is finished with a refined elongated metal temple, sculpted to form the signature Le Specs Luxe claw profile as it extends from...', 4064000, 12, 'products/numero-diez-champagne-velvet.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'chu-nhat-rectangle'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'numero-diez-champagne-velvet');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Numero Diez', 'numero-diez-obsidian-black', 'With strong, sharp lines and refined narrow proportions, our NÚMERO DIEZ sunglasses deliver a confident and elevated interpretation of the modern rectangular silhouette. Featuring an ultra-flat 0-base lens and meticulous chamfering throughout, this frame is crafted from bespoke custom 8mm & 6mm acetates, balancing bold structure with subtle refinement. This frame is finished with a refined elongated metal temple, sculpted to form the signature Le Specs Luxe claw profile as it extends from...', 4064000, 19, 'products/numero-diez-obsidian-black.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'chu-nhat-rectangle'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'numero-diez-obsidian-black');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Armada', 'armada-black-lsp1902089', 'Lending a soft and glamourous take to the classic cat eye, this flattering silhouette is the perfect ‘everyday’ sunglass. Finished with a fine-framed profile and iconic Le Specs flagstripe metal hardware.
- Finished in a black frame with smoke gradient lenses.
- Made using BPA free polymer plastic which is lightweight, durable and impact resistant.
- Fitted with shatterproof and scratch resistant polycarbonate lenses.', 1651000, 45, 'products/armada-black-lsp1902089.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'tron-round'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'armada-black-lsp1902089');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Majestic', 'majestic-black-polarised', 'Smooth and refined, MAJESTIC elevates the classic feminine silhouette with a gently contoured brow line and sculpted curves. Designed for a graceful, easy fit, this style is balanced with streamlined temples and finished with Le Specs’ signature metal detailing for a polished contemporary look.
- Finished in a black frame with smoke mono polarized lenses.
- A lightweight, durable and impact resistant polycarbonate frame.
- Fitted with polarised lenses to eliminate unwanted reflective glare.', 1905000, 45, 'products/majestic-black-polarised.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'tron-round'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'majestic-black-polarised');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Paramount', 'paramount-milky-tort-brown-grad-lsp1502050', 'Oversized and feminine, our PARAMOUNT sunglasses offer an everyday look for all face shapes. This refined glamourous round style is designed with a modern flat profile and iconic Le Specs flag stripe metal hardware on both temples.
- Finished in a milky tort frame with brown gradient lenses.
- Made using BPA free polymer plastic which is lightweight, durable and impact resistant.
- Fitted with shatterproof and scratch resistant polycarbonate lenses.', 1651000, 42, 'products/paramount-milky-tort-brown-grad-lsp1502050.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'tron-round'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'paramount-milky-tort-brown-grad-lsp1502050');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Majestic', 'majestic-coco', 'Smooth and refined, MAJESTIC elevates the classic feminine silhouette with a gently contoured brow line and sculpted curves. Designed for a graceful, easy fit, this style is balanced with streamlined temples and finished with Le Specs’ signature metal detailing for a polished contemporary look.
- Finished in a coco frame with khaki gradient lenses.
- A lightweight, durable and impact resistant polycarbonate frame.
- Fitted with shatterproof and scratch resistant polycarbonate lenses.', 1651000, 8, 'products/majestic-coco.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'tron-round'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'majestic-coco');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Numero Ocho', 'numero-ocho-teak', 'Sharp, sculptural, and unapologetically bold, NUMERO OCHO is defined by its angular contours and confident attitude. Made from bespoke custom 8mm & 6mm acetates, this frame highlights delicate chamfering detail meticulously added to every aspect of the frame, providing a soft and rounded luxurious, hand polished look and feel. Each pair is finished with Le Specs signature three dimensionally crafted infinity flagstripe metal decal and iconic single flagstripe inspired rounded rivet offering...', 2794000, 41, 'products/numero-ocho-teak.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'khien-shield'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'numero-ocho-teak');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Veiled', 'veiled-bright-gold-sand', 'Revisit the essence of noughties glamour with our VEILED shield sunglasses, a bold statement piece that merges nostalgia with modern sophistication. Designed with captivating oversized proportions and a sleek, wrapped profile, this midsize frame offers a flattering fit that contours effortlessly to the face. Elevated with exquisite inlaid tricrystal hardware detailing at the temples, VEILED exudes a sense of refined opulence.
- Finished in a bright gold and sand frame with tan gradient w...', 1524000, 42, 'products/veiled-bright-gold-sand.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'khien-shield'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'veiled-bright-gold-sand');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Numero Ocho', 'numero-ocho-pink-salt', 'Sharp, sculptural, and unapologetically bold, NUMERO OCHO is defined by its angular contours and confident attitude. Made from bespoke custom 8mm & 6mm acetates, this frame highlights delicate chamfering detail meticulously added to every aspect of the frame, providing a soft and rounded luxurious, hand polished look and feel. Each pair is finished with Le Specs signature three dimensionally crafted infinity flagstripe metal decal and iconic single flagstripe inspired rounded rivet offering...', 2032000, 30, 'products/numero-ocho-pink-salt.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'khien-shield'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'numero-ocho-pink-salt');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Numero Ocho', 'numero-ocho-obsidian-black', 'Sharp, sculptural, and unapologetically bold, NUMERO OCHO is defined by its angular contours and confident attitude. Made from bespoke custom 8mm & 6mm acetates, this frame highlights delicate chamfering detail meticulously added to every aspect of the frame, providing a soft and rounded luxurious, hand polished look and feel. Each pair is finished with Le Specs signature three dimensionally crafted infinity flagstripe metal decal and iconic single flagstripe inspired rounded rivet offering...', 2794000, 8, 'products/numero-ocho-obsidian-black.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'khien-shield'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'numero-ocho-obsidian-black');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Incantation', 'incantation-black', 'Designed with a nod to the effortless glamour of the 70s, INCANTATION is a statement-making silhouette that feels both feminine and flattering. Featuring an oversized frame and refined detailing, this style brings a touch of vintage allure while remaining modern and wearable.
- Finished in a black frame with smoke mono lenses.
- Made using BPA free polymer plastic which is lightweight, durable and impact resistant.
- Fitted with shatterproof and scratch resistant polycarbonate lenses.', 1651000, 19, 'products/incantation-black.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'vuong-square'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'incantation-black');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'The Illusion', 'the-illusion-tort', 'Timelessly elegant and effortlessly chic, our THE ILLUSION sunglasses infuse a sophisticated European sensibility into the classic square silhouette. Designed with an oversized fit that flatters all face shapes, this style is refined with luxurious heritage flagstripe metal hardware and subtle bevel detailing.
- Finished in a tort frame with khaki gradient lenses.
- A lightweight, durable and impact resistant polycarbonate frame.
- Fitted with shatterproof and scratch resistant polycarbonate...', 1905000, 7, 'products/the-illusion-tort.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'vuong-square'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'the-illusion-tort');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Elixir', 'elixir-khaki', 'Inspired by contemporary culture, our ELIXIR sunglasses offer a modern update to the classic square silhouette. Featuring a bold bevelled front and sleek lines, this midsize frame delivers balanced proportions and is finished with Le Specs’ signature metal temple detailing for a polished edge.
- Finished in a khaki frame with khaki green lenses.
- A lightweight, durable and impact resistant polycarbonate frame.
- Fitted with shatterproof and scratch resistant polycarbonate lenses.', 1905000, 40, 'products/elixir-khaki.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'vuong-square'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'elixir-khaki');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Elixir', 'elixir-dark-chocolate', 'Inspired by contemporary culture, our ELIXIR sunglasses offer a modern update to the classic square silhouette. Featuring a bold bevelled front and sleek lines, this midsize frame delivers balanced proportions and is finished with Le Specs’ signature metal temple detailing for a polished edge.
- Finished in a dark chocolate frame with smokey brown mono lenses.
- A lightweight, durable and impact resistant polycarbonate frame.
- Fitted with shatterproof and scratch resistant polycarbonate lenses.', 1905000, 59, 'products/elixir-dark-chocolate.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'vuong-square'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'elixir-dark-chocolate');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Bubbles', 'bubbles-gold-moss-mono', 'Designed with a sleek, angular wraparound silhouette, BUBBLES brings a directional edge to classic rimless styling. The curved lenses are contrasted by sharp and sleek lines, giving the cat eye frame a futuristic, high-gloss finish. Crafted with adjustable nose pads for a tailored fit, this style is finished with slimline metal temples that feature cut out flag stripe logos to temple ends.
- Finished in a gold frame with moss mono lenses.
- Sturdy metal frame fitted with allergy-free...', 2159000, 13, 'products/bubbles-gold-moss-mono.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'wrap'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'bubbles-gold-moss-mono');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Bubbles', 'bubbles-gold-amber-tint-w-silver-flash', 'Designed with a sleek, angular wraparound silhouette, BUBBLES brings a directional edge to classic rimless styling. The curved lenses are contrasted by sharp and sleek lines, giving the cat eye frame a futuristic, high-gloss finish. Crafted with adjustable nose pads for a tailored fit, this style is finished with slimline metal temples that feature cut out flag stripe logos to temple ends.
- Finished in a gold frame with amber tint silver flash lenses.
- Sturdy metal frame fitted with...', 2413000, 23, 'products/bubbles-gold-amber-tint-w-silver-flash.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'wrap'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'bubbles-gold-amber-tint-w-silver-flash');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Bubbles', 'bubbles-gold-sky-blue-grad', 'Designed with a sleek, angular wraparound silhouette, BUBBLES brings a directional edge to classic rimless styling. The curved lenses are contrasted by sharp and sleek lines, giving the cat eye frame a futuristic, high-gloss finish. Crafted with adjustable nose pads for a tailored fit, this style is finished with slimline metal temples that feature cut out flag stripe logos to temple ends.
- Finished in a gold frame with sky blue gradient lenses.
- Sturdy metal frame fitted with allergy-free...', 2159000, 31, 'products/bubbles-gold-sky-blue-grad.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'wrap'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'bubbles-gold-sky-blue-grad');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Bubbles', 'bubbles-gold-smokey-pink-grad', 'Designed with a sleek, angular wraparound silhouette, BUBBLES brings a directional edge to classic rimless styling. The curved lenses are contrasted by sharp and sleek lines, giving the cat eye frame a futuristic, high-gloss finish. Crafted with adjustable nose pads for a tailored fit, this style is finished with slimline metal temples that feature cut out flag stripe logos to temple ends.
- Finished in a gold frame with smokey pink gradient lenses.
- Sturdy metal frame fitted with...', 2159000, 14, 'products/bubbles-gold-smokey-pink-grad.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'wrap'), NULL, 'nu' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'bubbles-gold-smokey-pink-grad');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Tragic Magic', 'tragic-magic-black-lsp2202448', 'Exuding a carefree spirit and effortless aesthetic, TRAGIC MAGIC is the must-have aviator sunglass for summer. This ''70s inspired silhouette offers a slightly oversized fit with flattering unisex proportions and is detailed with our understated pyramid stud hardware on both temples.
- Finished in a black frame with tan tint lenses.
- Made using BPA free polymer plastic which is lightweight, durable and impact resistant.
- Fitted with shatterproof and scratch resistant polycarbonate lenses.', 1778000, 39, 'products/tragic-magic-black-lsp2202448.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'phi-cong-aviator'), NULL, 'unisex' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'tragic-magic-black-lsp2202448');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Le Gars +', 'le-gars-black-smoke-mono-polarised', 'Designed for impact and comfort, LE GARS redefines the aviator silhouette with a bold, structured shape tailored for broader face shapes. This wearable, unisex frame is finished with discreet classic Le Specs flagstripe hardware to its fine temples.
- Finished in a black frame with smoke mono polarized lenses.
- A lightweight, durable and impact resistant polycarbonate frame.
- Fitted with polarized lenses to eliminate unwanted reflective glare.', 2159000, 12, 'products/le-gars-black-smoke-mono-polarised.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'phi-cong-aviator'), NULL, 'unisex' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'le-gars-black-smoke-mono-polarised');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'The Duke', 'the-duke-matte-black', 'Crafted with contemporary details and timeless proportions, THE DUKE aviator sunglasses are your ideal pair of versatile and standout look. Highlighting an innovative flat lens and designed to flatter all face shapes, this style is finished with sleek and refined metal temples and adjustable nose pads for a personalized and comfortable fit.
- Finished in a matte black frame with intense smoke gradient lenses.
- Sturdy metal frame fitted with allergy-free cushioned PVC nose pads.
- Fitted...', 1016000, 41, 'products/the-duke-matte-black.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'phi-cong-aviator'), NULL, 'unisex' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'the-duke-matte-black');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Freigeist', 'freigeist-dark-green', 'Sculpted and enveloping, FREIGEIST combines fluid contours with a sharp industrial edge to deliver a commanding silhouette. Soft, continuous curves wrap the face in a sense of movement, while precise structural detailing introduces a bold, mechanical contrast. The result is a frame that feels both refined and assertive.
- Finished in a dark green frame with green mono lenses.', 4064000, 24, 'products/freigeist-dark-green.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'mat-meo-cat-eye'), NULL, 'unisex' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'freigeist-dark-green');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Freigeist', 'freigeist-scratched-black', 'Sculpted and enveloping, FREIGEIST combines fluid contours with a sharp industrial edge to deliver a commanding silhouette. Soft, continuous curves wrap the face in a sense of movement, while precise structural detailing introduces a bold, mechanical contrast. The result is a frame that feels both refined and assertive.
- Finished in a scratched black frame with chestnut mono lenses.', 4064000, 40, 'products/freigeist-scratched-black.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'mat-meo-cat-eye'), NULL, 'unisex' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'freigeist-scratched-black');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Freigeist', 'freigeist-black', 'Sculpted and enveloping, FREIGEIST combines fluid contours with a sharp industrial edge to deliver a commanding silhouette. Soft, continuous curves wrap the face in a sense of movement, while precise structural detailing introduces a bold, mechanical contrast. The result is a frame that feels both refined and assertive.
- Finished in a black frame with smoke mono lenses.', 4064000, 57, 'products/freigeist-black.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'mat-meo-cat-eye'), NULL, 'unisex' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'freigeist-black');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Racketeer', 'racketeer-matte-tort-smoke-mono-lsp1802446', 'Defined by its bespoke metal encased construction, this fine-framed silhouette features a masculine edge with its matte texture frame. Fitted with spring hinges and adjustable nose pads for a tailored fit.
- Finished in a matte tort frame with smoke mono lenses.
- Made using BPA free polymer plastic which is lightweight, durable and impact resistant.
- Fitted with shatterproof and scratch resistant polycarbonate lenses.', 1016000, 48, 'products/racketeer-matte-tort-smoke-mono-lsp1802446.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'd-frame'), NULL, 'unisex' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'racketeer-matte-tort-smoke-mono-lsp1802446');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Cubito +', 'cubito-tort', 'Cubito is a structured square frame with bold proportions and sharp lines. Its thick-set silhouette and defined angles give it a strong, confident presence, while the flatter brow and wider temples reinforce its modernist edge. A statement style that blends classic square eyewear with contemporary attitude, this frame is finished with a horizontal inlaid hardware with debossed flagstripe and rivet detailing.
- Finished in a tort frame with brown mono lenses.
- A lightweight, durable and...', 1905000, 16, 'products/cubito-tort.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'd-frame'), NULL, 'unisex' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'cubito-tort');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Nocturnal Habit', 'nocturnal-habit-vermilion', 'A contemporary update to the classic D-frame, our NOCTURNAL HABIT sunglasses deliver a bold look. With larger proportions and a striking flat frame profile, this pair is accented with horizontal stripe flagstripe hardware and subtle bevel detailing.
- Finished in a vermilion 2552194 frame with crimson tint lenses.
- A lightweight, durable and impact resistant polycarbonate frame.
- Fitted with shatterproof and scratch resistant polycarbonate lenses.', 508000, 11, 'products/nocturnal-habit-vermilion.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'd-frame'), NULL, 'unisex' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'nocturnal-habit-vermilion');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Wanderlust', 'wanderlust-scratched-black', 'WANDERLUST is angular and unapologetic, anchored by engineered temples inspired by the raw precision of mechanical hardware. The sharp, defined silhouette strikes a confident attitude, while structural detailing along the temples introduces industrial edge.
- Finished in a scratched black frame with chestnut mono lenses.', 4064000, 42, 'products/wanderlust-scratched-black.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'oval'), NULL, 'unisex' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'wanderlust-scratched-black');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Body Bumpin Ii', 'body-bumpin-ii-black-olive', 'Offering a modern update to the minimalistic 90s look, our BODY BUMPIN II sunglasses are designed with a wide fit, narrow aesthetic and slightly wrapped silhouette. Finished with Le Specs geometric flag stripe buckle hardware on both temples, these frames are a wardrobe staple.
- Finished in a black frame with olive mono lenses.
- A lightweight, durable and impact resistant polycarbonate frame.
- Fitted with shatterproof and scratch resistant polycarbonate lenses.', 508000, 41, 'products/body-bumpin-ii-black-olive.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'oval'), NULL, 'unisex' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'body-bumpin-ii-black-olive');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Foundry +', 'foundry-whiskey', 'A narrow, modern oval silhouette, FOUNDRY is a sleek, streamlined profile with a strong directional feel. Featuring soft bevelled detail and subtle double rivet detailing to front frame, this frame is finished with our classic Le Specs flagstripe pin badge.
- Finished in a whiskey frame with light brown mono lenses.', 1651000, 45, 'products/foundry-whiskey.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'oval'), NULL, 'unisex' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'foundry-whiskey');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Gigglemug', 'gigglemug-tort', 'Inspired by early-2000s attitude, our GIGGLEMUG sunglasses deliver a fresh take on the slim rectangular silhouette. Featuring smooth sculpted edges and a streamlined profile, this midsize frame offers sharp unisex proportions and is finished with Le Specs’ signature metal temple detail for a clean modern look.
- Finished in a tort frame with brown mono lenses.
- A lightweight, durable and impact resistant polycarbonate frame.
- Fitted with shatterproof and scratch resistant polycarbonate lenses.', 1651000, 17, 'products/gigglemug-tort.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'chu-nhat-rectangle'), NULL, 'unisex' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'gigglemug-tort');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Blackpool', 'blackpool-matte-black-khaki-grad', 'Designed with a contemporary rectangular shape, the BLACKPOOL sunglasses are designed with narrow proportions and wide fit for all face sizes. This unisex frame features soft bevelled details and sleek tapered temples and is finished with No Problemo logo print to temple. 
- Finished in a matte black and khaki grad frame with smoke tint lenses.
- A lightweight, durable and impact resistant polycarbonate frame.
- Fitted with shatterproof and scratch resistant polycarbonate lenses.', 2794000, 28, 'products/blackpool-matte-black-khaki-grad.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'chu-nhat-rectangle'), NULL, 'unisex' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'blackpool-matte-black-khaki-grad');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Dopamine', 'dopamine-milky-almond', 'With exaggerated angles and dramatic chamfering detail, our DOPAMINE sunglasses are a new season wardrobe must have. Designed with a widefit, this oversized rectangle frame features Le Specs geometric flagstripe buckle hardware on both temples.
- Finished in a milky almond frame with moss mono lenses.
- A lightweight, durable and impact resistant polycarbonate frame.
- Fitted with shatterproof and scratch resistant polycarbonate lenses.', 508000, 11, 'products/dopamine-milky-almond.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'chu-nhat-rectangle'), NULL, 'unisex' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'dopamine-milky-almond');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Invincible', 'invincible-tokyo-tort', 'Lightweight and dynamic, INVINCIBLE brings a fresh energy to the classic round silhouette with its smooth contoured front and streamlined profile. Designed for a versatile unisex fit, this style is balanced with slim temples and finished with subtle detailing that delivers a clean, modern edge.
- Finished in a tokyo tort frame with navy mono lenses.
- A lightweight, durable and impact resistant polycarbonate frame.
- Fitted with shatterproof and scratch resistant polycarbonate lenses.', 1905000, 40, 'products/invincible-tokyo-tort.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'tron-round'), NULL, 'unisex' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'invincible-tokyo-tort');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Heart Throb', 'heart-throb-mist', 'Bold with a nostalgic twist, HEART THROB reimagines the classic round silhouette into a clean, modern unisex staple. Designed with smooth contoured lines and wide temples, this shape delivers a balanced fit and is finished with subtle metal detailing for a polished everyday edge.
- Finished in a mist frame with amber tint lenses.
- A lightweight, durable and impact resistant polycarbonate frame.
- Fitted with shatterproof and scratch resistant polycarbonate lenses.', 1524000, 50, 'products/heart-throb-mist.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'tron-round'), NULL, 'unisex' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'heart-throb-mist');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Fire Starter', 'fire-starter-matte-tort-lsp2002218', 'FIRE STARTER reimagines mid-century style with a contemporary edge. Defined by its round lenses and keyhole nose bridge, this mid-size classic is elevated with the iconic Le Specs flag stripe metal hardware, blending timeless design with modern sophistication.
- Finished in a matte tort frame with khaki mono polarized lenses.
- Made using BPA free polymer plastic which is lightweight, durable and impact resistant.
- Fitted with polarized lenses to eliminate unwanted reflective glare.', 1905000, 9, 'products/fire-starter-matte-tort-lsp2002218.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'tron-round'), NULL, 'unisex' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'fire-starter-matte-tort-lsp2002218');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Flux', 'flux-mist', 'Designed with sleek, sweeping proportions, the FLUX wrap-around shield sunglasses reinterpret vintage performance eyewear through a contemporary fashion lens. The contoured, face-hugging silhouette features subtle cut-out lens accents, framed by a three-dimensionally moulded profile that flows seamlessly around the face.
The sculptural shape extends into thick, modular-style temples with a gentle S-curve, creating an ergonomic, sport-influenced fit that feels considered rather than...', 3556000, 41, 'products/flux-mist.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'khien-shield'), NULL, 'unisex' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'flux-mist');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Flux', 'flux-chrome-dark-green', 'Designed with sleek, sweeping proportions, the FLUX wrap-around shield sunglasses reinterpret vintage performance eyewear through a contemporary fashion lens. The contoured, face-hugging silhouette features subtle cut-out lens accents, framed by a three-dimensionally moulded profile that flows seamlessly around the face.
The sculptural shape extends into thick, modular-style temples with a gentle S-curve, creating an ergonomic, sport-influenced fit that feels considered rather than...', 3556000, 8, 'products/flux-chrome-dark-green.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'khien-shield'), NULL, 'unisex' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'flux-chrome-dark-green');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Vortex Deux', 'vortex-deux-dark-cherry', 'Designed with smooth, sculptural proportions, the VORTEX DEUX sunglasses are an elongated oval shield, that takes inspiration from best-selling elements of the No Problemo x Le Specs first collaboration.
Featuring thick, modular-style temples with a gentle S-curve, creating an ergonomic, sport-influenced fit that feels considered rather than technical, this frame is defined by No Problemo signature logo pad print to centre front lens. Finished with iconic three-dimensionally crafted No...', 3302000, 44, 'products/vortex-deux-dark-cherry.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'khien-shield'), NULL, 'unisex' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'vortex-deux-dark-cherry');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Mythic', 'mythic-gold-blue-light-lens', 'Defined by its geometric silhouette and slimline metal construction, MYTHIC octagonal sunglasses are a modern classic with sharp appeal. The unique lens shape offers a clean, angular finish, while the tapered temples and adjustable nose pads ensure a tailored fit. This frame is finished with our signature flag stripe mono block end piece and sleek slimline metal temples.
- Finished in a gold frame.
- Sturdy metal frame fitted with allergy-free cushioned PVC nose pads.
- Fitted with anti-blue...', 2159000, 18, 'products/mythic-gold-blue-light-lens.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'vuong-square'), NULL, 'unisex' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'mythic-gold-blue-light-lens');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Neptune Deux', 'neptune-deux-gold-lsp2002166', 'NEPTUNE DEUX offers a classic square silhouette with small proportions, making it the perfect ‘everyday’ sunglass for all face shapes. Its timeless design blends style with practicality, elevating any look with effortless sophistication.
- Finished in a gold frame with khaki mono polarized lenses.
- Sturdy metal frame fitted with allergy-free cushioned PVC nose pads. 
- Fitted with polarized lenses to eliminate unwanted reflective glare.', 2286000, 36, 'products/neptune-deux-gold-lsp2002166.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'vuong-square'), NULL, 'unisex' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'neptune-deux-gold-lsp2002166');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Impossible', 'impossible-tokyo-tort', 'Designed with a rounded profile and wide proportions for allface sizes, our IMPOSSIBLE rectangular frame sunglasses area wardrobe staple for both guys and girls. Offering a classic nineties inspired look, this unisex sunglass features discreet LeSpecs metal stud detailing on both temples.
- Finished in a tokyo tort frame with smoke mono lenses.
- A lightweight, durable and impact resistant polycarbonate frame.
- Fitted with shatterproof and scratch resistant polycarbonate lenses.', 1778000, 48, 'products/impossible-tokyo-tort.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'vuong-square'), NULL, 'unisex' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'impossible-tokyo-tort');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Star Beam', 'star-beam-bright-gold-khaki-mono', 'Giving a whole lotta Y2K energy, our STAR BEAM metal sunglasses give so much understated millennial attitude. Designed with three-dimensionally crafted bevelled metal temples and paddle tips, this small oval style features adjustable nose pads for a bespoke fit.
- Finished in a bright gold frame with khaki mono lenses.
- Sturdy metal frame fitted with allergy-free cushioned PVC nose pads. 
- Fitted with shatterproof and scratch resistant polycarbonate lenses.', 2159000, 39, 'products/star-beam-bright-gold-khaki-mono.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'wrap'), NULL, 'unisex' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'star-beam-bright-gold-khaki-mono');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Du Jour', 'du-jour-optic-white', 'A refined essential with a subtle nod to early 2000s styling, DU JOUR is a modern take on the wraparound silhouette. Designed for all-day wear with a lightweight, sleek, and contoured fit, this frame features streamlined temples and signature Le Specs vertical pinstripe hinge inlay
hardware.
- Finished in an optic white frame with smoke mono lenses.
- A lightweight, durable and impact resistant polycarbonate frame.
- Fitted with shatterproof and scratch resistant polycarbonate lenses.', 1016000, 32, 'products/du-jour-optic-white.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'wrap'), NULL, 'unisex' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'du-jour-optic-white');
INSERT INTO products_product (name, slug, description, price, stock_quantity, image, is_active, created_at, updated_at, category_id, created_by_id, gender) SELECT 'Du Jour', 'du-jour-black-smoke-mono', 'A refined essential with a subtle nod to early 2000s styling, DU JOUR is a modern take on the wraparound silhouette. Designed for all-day wear with a lightweight, sleek, and contoured fit, this frame features streamlined temples and signature Le Specs vertical pinstripe hinge inlay
hardware.
- Finished in a black frame with smoke mono lenses.
- A lightweight, durable and impact resistant polycarbonate frame.
- Fitted with shatterproof and scratch resistant polycarbonate lenses.', 1905000, 54, 'products/du-jour-black-smoke-mono.jpg', 1, NOW(), NOW(), (SELECT id FROM products_category WHERE slug = 'wrap'), NULL, 'unisex' WHERE NOT EXISTS (SELECT 1 FROM products_product WHERE slug = 'du-jour-black-smoke-mono');
