# Generated by Django 4.2.23 on 2026-07-31 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_product_care_instructions_product_sku_product_specs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('products', models.ManyToManyField(blank=True, help_text='Các sản phẩm mà người dùng này đã thêm vào danh sách yêu thích.', related_name='favorited_by', to='products.product', verbose_name='Sản phẩm yêu thích')),
                ('user', models.OneToOneField(help_text='Mỗi người dùng chỉ có đúng một danh sách yêu thích.', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Danh sách yêu thích',
                'verbose_name_plural': 'Danh sách yêu thích',
            },
        ),
    ]
