# Generated by Django 4.2.23 on 2026-09-11 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_alter_category_slug_alter_product_category_and_more'),
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='products.product', verbose_name='Sản phẩm yêu thích'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
    ]
