# Generated by Django 4.2.23 on 2026-09-10 04:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
        ('products', '0003_product_care_instructions_product_sku_product_specs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Số sao')),
                ('content', models.TextField(verbose_name='Nội dung đánh giá')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Bật thì KHÔNG hiển thị tên người dùng công khai (hệ thống vẫn biết là ai).', verbose_name='Ẩn danh')),
                ('sentiment', models.CharField(blank=True, choices=[('POS', 'Tích cực'), ('NEU', 'Trung lập'), ('NEG', 'Tiêu cực')], help_text='Do mô hình học máy tự động gán khi lưu đánh giá.', max_length=3, verbose_name='Nhãn cảm xúc (AI)')),
                ('sentiment_confidence', models.FloatField(blank=True, help_text='Xác suất lớn nhất trong 3 lớp - CHỈ dùng nội bộ/admin, không hiển thị cho khách.', null=True, verbose_name='Độ tin cậy dự đoán')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đánh giá')),
                ('order_item', models.ForeignKey(help_text='Dòng đơn hàng (đã giao thành công) chứng minh người này đã mua sản phẩm.', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.orderitem', verbose_name='Bằng chứng đã mua')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='Sản phẩm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá')),
            ],
            options={
                'verbose_name': 'Đánh giá sản phẩm',
                'verbose_name_plural': 'Đánh giá sản phẩm',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ReviewMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reviews/%Y/%m/', verbose_name='File')),
                ('media_type', models.CharField(choices=[('image', 'Ảnh'), ('video', 'Video')], max_length=5, verbose_name='Loại file')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='reviews.review', verbose_name='Đánh giá')),
            ],
            options={
                'verbose_name': 'Ảnh/video đánh giá',
                'verbose_name_plural': 'Ảnh/video đánh giá',
            },
        ),
    ]
