# Generated by Django 4.2.23 on 2026-09-11 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_delivery_status_and_more'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='Ẩn danh'),
        ),
        migrations.AlterField(
            model_name='review',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.orderitem', verbose_name='Bằng chứng đã mua'),
        ),
        migrations.AlterField(
            model_name='review',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('POS', 'Tích cực'), ('NEU', 'Trung lập'), ('NEG', 'Tiêu cực')], max_length=3, verbose_name='Nhãn cảm xúc (AI)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='sentiment_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Độ tin cậy dự đoán'),
        ),
    ]
