# Generated by Django 4.2.23 on 2026-09-23 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_delivery_status_and_more'),
        ('reviews', '0002_alter_review_is_anonymous_alter_review_order_item_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='review',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.orderitem', verbose_name='Bằng chứng đã mua'),
        ),
    ]
