# Generated by Django 6.0.6 on 2026-07-12 16:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Số dư hiện tại trong ví, luôn được đảm bảo lớn hơn hoặc bằng 0.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Số dư (VNĐ)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo ví')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần cập nhật gần nhất')),
                ('user', models.OneToOneField(help_text='Mỗi người dùng chỉ có đúng một ví điện tử.', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Ví điện tử',
                'verbose_name_plural': 'Ví điện tử',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Nạp tiền'), ('PAYMENT', 'Thanh toán')], max_length=10, verbose_name='Loại giao dịch')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Luôn là số dương, chiều tăng/giảm số dư được xác định bởi transaction_type.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Số tiền giao dịch (VNĐ)')),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Số dư của ví ngay SAU KHI giao dịch này hoàn tất, dùng để tra soát đối chiếu.', max_digits=14, verbose_name='Số dư sau giao dịch (VNĐ)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian giao dịch')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet', verbose_name='Ví điện tử')),
            ],
            options={
                'verbose_name': 'Giao dịch ví điện tử',
                'verbose_name_plural': 'Lịch sử giao dịch ví điện tử',
                'ordering': ['-created_at'],
            },
        ),
    ]
