# Generated by Django 4.2.23 on 2026-09-10 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, help_text='Chỉ có giá trị khi giỏ hàng thuộc về khách chưa đăng nhập.', max_length=40, null=True, unique=True, verbose_name='Khóa phiên (khách vãng lai)'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Để trống nếu đây là giỏ hàng của khách vãng lai (chưa đăng nhập).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
    ]
