# Generated by Django 4.2.23 on 2026-09-10 04:12

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_product_care_instructions_product_sku_product_specs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DELIVERED', 'Giao hàng thành công')], default='DELIVERED', help_text='Đồ án không mô phỏng vận chuyển, đơn luôn ở trạng thái đã giao thành công.', max_length=20, verbose_name='Trạng thái đơn hàng')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Tổng tiền đã trừ trong ví tại thời điểm đặt hàng.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tổng tiền đơn hàng (VNĐ)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt hàng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Người mua')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Giá sản phẩm tại thời điểm mua, không đổi theo giá hiện tại của sản phẩm.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Đơn giá lúc mua (VNĐ)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Đơn hàng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Sản phẩm trong đơn hàng',
                'verbose_name_plural': 'Sản phẩm trong đơn hàng',
            },
        ),
    ]
