# Generated by Django 4.2.23 on 2026-09-10 07:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng (COD)'), ('MOMO', 'Ví MoMo'), ('CARD', 'Thẻ ngân hàng')], default='COD', help_text='Đồ án GIẢ LẬP bước thanh toán (chưa nối cổng thanh toán thật) - chỉ ghi lại hình thức người dùng chọn.', max_length=10, verbose_name='Hình thức thanh toán'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tổng tiền đơn hàng (VNĐ)'),
        ),
    ]
