# Generated by Django 4.2.23 on 2026-09-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_method_alter_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipient_phone',
            field=models.CharField(default='', max_length=15, verbose_name='SĐT người nhận'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(default='', help_text='Bắt buộc nhập trước khi thanh toán - lưu lại đúng địa chỉ tại thời điểm đặt hàng (khác với địa chỉ mặc định trong hồ sơ, vì người dùng có thể đổi sau này).', max_length=255, verbose_name='Địa chỉ nhận hàng'),
        ),
    ]
