# Generated by Django 4.2.23 on 2026-09-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_recipient_phone_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(default='', max_length=100, verbose_name='Tên người nhận'),
        ),
    ]
