# Generated by Django 4.2.23 on 2026-09-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_recipient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DELIVERED', 'Giao hàng thành công'), ('CANCELLED', 'Đã hủy')], default='DELIVERED', help_text='Đồ án không mô phỏng vận chuyển nhiều bước - đơn mới đặt luôn ở trạng thái đã giao thành công, người mua có thể tự hủy sau đó.', max_length=20, verbose_name='Trạng thái đơn hàng'),
        ),
    ]
