# Generated by Django 4.2.23 on 2026-09-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('PENDING', 'Chờ giao hàng'), ('IN_TRANSIT', 'Đang trên đường vận chuyển'), ('DELIVERED', 'Giao hàng thành công'), ('FAILED', 'Giao hàng thất bại')], default='DELIVERED', help_text='Admin có thể cập nhật khi đơn vị vận chuyển báo tiến trình giao hàng thay đổi.', max_length=20, verbose_name='Trạng thái giao hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_carrier',
            field=models.CharField(choices=[('GHN', 'Giao Hàng Nhanh (GHN)'), ('GHTK', 'Giao Hàng Tiết Kiệm (GHTK)'), ('SPX', 'SPX Express'), ('VIETTEL_POST', 'Viettel Post'), ('JT', 'J&T Express')], default='GHN', max_length=20, verbose_name='Đơn vị vận chuyển'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng (COD)'), ('MOMO', 'Ví MoMo'), ('CARD', 'Thẻ ngân hàng')], default='COD', max_length=10, verbose_name='Hình thức thanh toán'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(default='', max_length=255, verbose_name='Địa chỉ nhận hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DELIVERED', 'Giao hàng thành công'), ('CANCELLED', 'Đã hủy')], default='DELIVERED', max_length=20, verbose_name='Trạng thái đơn hàng'),
        ),
    ]
