# Generated by Django 4.2.23 on 2026-09-11 06:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_delivery_status_order_shipping_carrier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('PENDING', 'Chờ giao hàng'), ('IN_TRANSIT', 'Đang trên đường vận chuyển'), ('DELIVERED', 'Giao hàng thành công'), ('FAILED', 'Giao hàng thất bại')], default='DELIVERED', max_length=20, verbose_name='Trạng thái giao hàng'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Đơn giá lúc mua (VNĐ)'),
        ),
    ]
