# Generated by Django 6.0.6 on 2026-07-12 16:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(blank=True, help_text='Tự động sinh ra từ tên danh mục, dùng để hiển thị trên URL (ví dụ: dien-thoai).', max_length=120, unique=True, verbose_name='Đường dẫn thân thiện')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Danh mục sản phẩm',
                'verbose_name_plural': 'Danh mục sản phẩm',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Đường dẫn thân thiện')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả sản phẩm')),
                ('price', models.DecimalField(decimal_places=2, help_text='Giá tiền phải lớn hơn hoặc bằng 0, dùng kiểu Decimal để không bị sai số.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Giá bán (VNĐ)')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('image', models.ImageField(blank=True, help_text='Ảnh sản phẩm được lưu vào thư mục media/products/.', null=True, upload_to='products/', verbose_name='Ảnh sản phẩm')),
                ('is_active', models.BooleanField(default=True, help_text='Bỏ tick để ẩn sản phẩm khỏi trang chủ mà không cần xóa hẳn dữ liệu.', verbose_name='Đang bày bán')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật gần nhất')),
                ('category', models.ForeignKey(help_text='Sản phẩm này thuộc danh mục nào.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Danh mục')),
                ('created_by', models.ForeignKey(blank=True, help_text='Tài khoản quản trị đã thêm sản phẩm này vào hệ thống.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'ordering': ['-created_at'],
            },
        ),
    ]
