# Generated by Django 4.2.23 on 2026-07-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('nu', 'Nữ'), ('nam', 'Nam'), ('unisex', 'Unisex')], default='unisex', help_text='Sản phẩm dành cho Nữ, Nam hay Unisex - dùng để lọc sản phẩm trên trang chủ.', max_length=10, verbose_name='Giới tính'),
        ),
    ]
