# Generated by Django 4.2.23 on 2026-07-13 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='care_instructions',
            field=models.TextField(blank=True, verbose_name='Hướng dẫn bảo quản'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Mã sản phẩm lấy từ nguồn dữ liệu gốc, dùng để tra soát/đối chiếu.', max_length=64, verbose_name='Mã sản phẩm (SKU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='specs',
            field=models.JSONField(blank=True, default=dict, help_text='Cặp key/value tự do (kích thước gọng, chất liệu, khả năng chống UV...).', verbose_name='Thông số kỹ thuật'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Ảnh')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Ảnh sản phẩm',
                'verbose_name_plural': 'Ảnh sản phẩm (gallery)',
                'ordering': ['position'],
            },
        ),
    ]
