# Generated by Django 4.2.23 on 2026-09-29 12:35

import uuid

from django.db import migrations, models
from django.utils.text import slugify


def fill_missing_skus(apps, schema_editor):
    # Sản phẩm cũ chưa có SKU (hoặc trùng) được sinh mã mới TRƯỚC khi đặt
    # ràng buộc UNIQUE - cùng định dạng với Product.generate_sku.
    Product = apps.get_model("products", "Product")
    used = set()
    for product in Product.objects.select_related("category").order_by("id"):
        sku = (product.sku or "").strip().upper()
        if not sku or sku in used:
            prefix = (slugify(product.category.name).replace("-", "")[:3] or "gen").upper()
            sku = f"AST-{prefix}-{uuid.uuid4().hex[:6].upper()}"
        used.add(sku)
        if sku != product.sku:
            product.sku = sku
            product.save(update_fields=["sku"])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_slug_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_missing_skus, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='Mã sản phẩm (SKU)'),
        ),
    ]
